# Generated by Django 4.0.4 on 2022-04-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=70)),
                ('latittude', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
