# Generated by Django 4.0.4 on 2022-04-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approch_road',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_details',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_from_orr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='extent_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='mandal',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='name_of_owner',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='near_market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='road_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='village_locality',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
